import { GET_POSTS_SUCCESS, GET_POSTS_REJECTED, ADD_POST_SUCCESS, ADD_POST_REJECTED, UPVOTE_POST_SUCCESS, DOWNVOTE_POST_SUCCESS } from './PostsType'

export { GET_POSTS_SUCCESS, GET_POSTS_REJECTED, ADD_POST_SUCCESS, ADD_POST_REJECTED, UPVOTE_POST_SUCCESS, DOWNVOTE_POST_SUCCESS }
