export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_REJECTED = 'GET_POSTS_REJECTED'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_REJECTED = 'ADD_POST_REJECTED'
